swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/transactions:
    get:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Current Month User Transaction API
      description: API for fetching current month user transactions 
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: Current month user transactions retrieved successully
          schema:
            $ref: '#/definitions/TransactionResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/transactions/details:
    get:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Specific User Transaction API
      description: API for fetching a specific user transaction 
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: body
          name: transactionId
          description: transaction id
          required: true
          schema:
            $ref: '#/definitions/TransactionDetails'
      produces:
        - application/json
      responses:
        '200':
          description: user transaction details retrieved successully
          schema:
            $ref: '#/definitions/TransactionResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Edit User Transaction API
      description: API for updating a user transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: body
          name: body
          description: Update user transaction attributes
          required: true
          schema:
            $ref: '#/definitions/TransactionEdit'
      produces:
        - application/json
      responses:
        '200':
          description: User transaction retrieved successully
          schema:
            $ref: '#/definitions/TransactionResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
          
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  TransactionResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
            description: transaction id
          date:
            type: string
            description: transaction date
          description:
            type: string
            description: transaction description
          amount:
            type: string
            description: transaction amount
          balance:
            type: string
            description: balance after transaction
          type:
            type: string
            description: transaction type
          category:
            type: string
            description: transaction category
          notes:
            type: string
            description: transaction notes
          accountId:
            type: string
            description: account type
  TransactionDetails:
    type: object
    properties:
      id:
        type: string
  TransactionEdit:
    type: object
    properties:
      category:
        type: string
      notes:
        type: string